function cellInfo = Formation_Cross_Bus(varargin) 
% FORMATION_CROSS_BUS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'Formation_Cross_Bus', ... 
    '', ... 
    sprintf('Supports up to 3 drone.'), ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'timestamp', 3, 'uint32', 'real', 'Sample', 'Fixed', [], [], sprintf('ms'), ''}; ...
{'x_R', 3, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'y_R', 3, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'h_R', 3, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'vn', 3, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'ve', 3, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'vd', 3, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
