function cellInfo = Mission_Data(varargin) 
% MISSION_DATA returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'Mission_Data_Bus', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'timestamp', 1, 'uint32', 'real', 'Sample', 'Fixed', [], [], sprintf('ms'), ''}; ...
{'type', 1, 'uint32', 'real', 'Sample', 'Fixed', [], [], '', sprintf('FormAssemble(1),\nFormDisband(2),\nFormMission(3),\nMission(4),')}; ...
{'valid_items', 1, 'uint8', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'x', 8, 'single', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'y', 8, 'single', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'z', 8, 'single', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'heading', 8, 'single', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ext1', 8, 'single', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ext2', 8, 'single', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
