function cellInfo = Other_INS_Out_Bus(varargin) 
% OTHER_INS_OUT_BUS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'Ctrl_Cmd_Bus', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'cmd_yaw', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cmd_vel', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cmd_height', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'INS_Out_Bus', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'timestamp', 1, 'uint32', 'real', 'Sample', 'Fixed', [], [], sprintf('ms'), ''}; ...
{'phi', 1, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'theta', 1, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'psi', 1, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'p', 1, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'q', 1, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'r', 1, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/s'), ''}; ...
{'quat', 4, 'single', 'real', 'Sample', 'Fixed', [], [], '', sprintf('Quaternion')}; ...
{'x_R', 1, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'y_R', 1, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'h_R', 1, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'ax', 1, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s2'), ''}; ...
{'ay', 1, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s2'), ''}; ...
{'az', 1, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s2'), ''}; ...
{'vn', 1, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'ve', 1, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'vd', 1, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
    } ...
  } ...
  { ... 
    'Other_INS_Out_Bus', ... 
    '', ... 
    sprintf('Supports up to 20 drone.'), ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'timestamp', 20, 'uint32', 'real', 'Sample', 'Fixed', [], [], sprintf('ms'), ''}; ...
{'x_R', 20, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'y_R', 20, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'h_R', 20, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m'), ''}; ...
{'vn', 20, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'ve', 20, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
{'vd', 20, 'single', 'real', 'Sample', 'Fixed', [], [], sprintf('m/s'), ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
